### ISSUE TITLE
Problem with type resolving

### ISSUE THREAD

**Issue by EloiMartinet** [cbritopacheco/rodin#28]
Hi,
In file examples/ShapeOptimization/LevelsetEigenvalue2D.cpp, when replacing line 143 by
```c++
auto dJ = (
  Dot(Grad(u).traceOf(Interior), Grad(u).traceOf(Interior))
  - mu * ScalarFunction(u) * ScalarFunction(u)
  - 2 * ell * (Omega.getVolume(Interior) - target_volume)) * n;
```
The compiler raises the error 
```c++
‘auto’ parameter not permitted in this context".
```

This apart, this library is amazing. ;)

Bye,
Eloi.

**Comment by cbritopacheco** [comment]
Hi Eloi, thank you for your report. On my machine this compiles just fine. Can you provide which compiler + version you are using ?

**Comment by EloiMartinet** [comment]
Hi,
Here is my compiler info :
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by cbritopacheco** [comment]
This bug is now stale and should probably work on the new version.
